[build]
  # Esta es la carpeta donde Netlify entra primero
  base = "frontend"
  
  # Como ya está dentro de "frontend", el comando es directo
  command = "npm run build"
  
  # ¡Aquí está el truco! Como ya está en "frontend", 
  # la ruta al resultado NO debe llevar el prefijo "frontend/"
  publish = "dist/frontend/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200